version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
cd 
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    command: bash -c "bundle exec rails db:prepare && bundle exec rails s -b 0.0.0.0 -p 3000"
    volumes:
      - ./backend:/app
    working_dir: /app
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      REDIS_URL: redis://redis:6379/0
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    command: npm run dev -- --host 0.0.0.0 --port 5173
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
