#ENC[AES256_GCM,data:SPiOv3j7RrEqY4cw7J8zaPrGiWVpW3wJ0AcYsQyeF4ZTQ7KeQ3I0meUdDqnHF1MdGo6GrwmAdp8T5f/S/FWkTDdOuo/DkFymySo9U2rgWolsxKTZQJQ20dWXbehS,iv:Oi5YkTaYweF9mc0gpVWzrGDQyd+lpdodWtezGwkJhVQ=,tag:0vK5rInKq/IVX+j+dROPcQ==,type:comment]
postgres:
    user: itsanproblem
    database: itsanproblem_production
    host: db
    port: 5432
    password: ENC[AES256_GCM,data:rWq9DaaCfxiSgGDjfXCbmuDavuaIrBmViXXUpf6Pr6Q1x9/EyuEARXFL6O+gP97r,iv:oi8622rTwVdog5+9SjKM3ddQKu35V3s+LTdksJISNGU=,tag:ErKVhtF3hycJOElV4M2A1A==,type:str]
jwt:
    secret_key: ENC[AES256_GCM,data:oyQMbsMtpJ1RK65tYqB/ygaqTgw3uzRIxYdtbfJHrUOGRBYh5ao0H9V8yWawdRobUE6VcU87YTIdCwX825ZfuO2pvNFBej6r8vPvbyTl3HZbiXYXwTHnQ5LqaGMKc+lsqyHR4EfwG+/AVMFeIi48ldHjJD04gOJFGEB6gAUK6GA=,iv:178mWlIE1b8NAqf71KAsb9jev3yuc2xOSfXf22I6TQg=,tag:txoXcgGJSyVlDI3SlH/GLg==,type:str]
secret_key_base: ENC[AES256_GCM,data:Xm9iS/6RdzBvyQtZzHE0r2bEr2p1igDQo9TrDmSPMV9UrG4Ttt3pRR6QntwB5mdXCHUbJTmJcbD+Pbg3AtmsW2q6TSIa3+bCd7FNkf4cBKE+e4CxTqTXkkotmNXnElXWzjedjpdrI8mzbi4apw5Fh1zFiOATa4Xbj996D0yqDxY=,iv:v1Ta/ynQw422bk2WGQOhJGfRb3bdnBb2POHa7xV9lf0=,tag:A08RgUsbjW2nZ2I93mEF+w==,type:str]
redis:
    url: ENC[AES256_GCM,data:gCSQIjVXUINl1+2PsskdmdlFvf2i,iv:PRH8nTNttXPEf71uCzCjAMWZRmiQmpYLcFhwVVEDghk=,tag:/TUNlu3oGFJNiA0P91AfHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SUtFRkROOUxydVhnQzM5
            NGptTU9CWVZPcjNuWHR1MU1Kb2VkRGgweFI0ClBmR3lxTTEyVXloWGVRK3EwV1dn
            RisvWW5JcXdwWVNUb1ZCcWpwTUlMK1EKLS0tIGQ5OGxCeVN0MzZyYVB6MlJGOEhk
            eVZMcnFhdThBczdWOHZzd1RKNWFvVXMKJfZm78MauDm41O206d9OBKGIjt4B9uBP
            fT6yVQA1tsBCtPsTpt7IOGZt2MIXU8764orAlNDs58inX4ceXoQi5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10e4t2qf24xrscvj72293s0f3fd5uqkd6f6wlv7ky86ds37d2n42q32vwlh
    lastmodified: "2026-06-10T10:10:07Z"
    mac: ENC[AES256_GCM,data:vZ2blJ3nhssr1zU+j1YYGH6lqe4Q3n8cGA3Bd4C3ufCz3D2FmcpZA9t6bjGcKHGi9Ng2l70EEMztzcU8NbnDd6J0KdBVYfCQPbjvQOcUU4ShTW9DnHFLcCd1arGyPakc2a1duaxbZKUdUaNN00r3uYS65vAjkiGjZFVoDeebiNs=,iv:164VUpuGgEkpcHjrRPrLjGx6o+hpPEz8Fgfv0JVi85g=,tag:4LxuxNGwOwSw0Li1K8p6Ow==,type:str]
    unencrypted_regex: ^(user|database|host|port)$
    version: 3.13.1
